import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: {
        absolute: '',
        default: 'Next App',
        template: '%s | Next App',
    },
    description: 'Generated by me',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const navTabs: {
        name: string;
        href: string;
    }[] = [
        {
            name: 'Home',
            href: '/',
        },
        {
            name: 'Docs',
            href: '/docs',
        },
        {
            name: 'About',
            href: '/about',
        },
        {
            name: 'Profile',
            href: '/profile',
        },
        {
            name: 'Login',
            href: '/login',
        },
        {
            name: 'Register',
            href: '/register',
        },
        {
            name: 'Product',
            href: '/product',
        },
        {
            name: '404',
            href: '/not-found',
        },
        {
            name: '500',
            href: '/server-error',
        },
    ];

    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiasedz`}
            >
                <header className=" w-full pt-10 pb-4">
                    <div className=" w-full flex items-center justify-center">
                        <nav className="flex justify-center flex-wrap max-w-[25rem] gap-4">
                            {navTabs.map(({ name, href }) => (
                                <Link
                                    key={name}
                                    className="text-sm bg-gradient-to-r from-slate-700 to-slate-800 hover:from-slate-700 hover:to-slate-700 transition-all px-2 py-1 hover:scale-110 rounded-md text-center sm:text-left font-[family-name:var(--font-geist-mono)]"
                                    href={href}
                                >
                                    {name}
                                </Link>
                            ))}
                        </nav>
                    </div>
                </header>

                {children}
            </body>
        </html>
    );
}
