import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
    src: './fonts/GeistVF.woff',
    variable: '--font-geist-sans',
    weight: '100 900',
});
const geistMono = localFont({
    src: './fonts/GeistMonoVF.woff',
    variable: '--font-geist-mono',
    weight: '100 900',
});

export const metadata: Metadata = {
    title: 'Next App',
    description: 'Generated by me',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiasedz space-y-16 h-screen w-screen bg-slate-950 flex flex-col justify-between items-center`}
            >
                <header className=" bg-slate-900 w-full py-24 pl-12 text-xl text-slate-300">
                    Header
                </header>

                <div className=" ring w-fit h-fit mx-auto">{children}</div>

                <footer className=" bg-slate-900 w-full py-24 pl-12 text-xl text-slate-300">
                    Footer
                </footer>
            </body>
        </html>
    );
}
